<div id="modal-ALT-01" class="modal">
  <div class="modal__container" style="width: 350px;">
    <div class="modal__content">
      <div class="modal-box__container">
        <div class="modal-box__content">
          <div class="modal__desc">
            <p class="modal__text">
              필수 항목이 입력되지 않았습니다.<br>다시 확인해주세요.
            </p>
          </div>
          <div class="modal__util">
            <button type="button" onclick="closeModal('#modal-ALT-01');" class="modal__button"><span>확인</span></button>
          </div>
          </div>
        </div>
      </div>
  </div>
</div>

<div id="modal-ALT-02" class="modal">
  <div class="modal__container" style="width: 350px;">
    <div class="modal__content">
      <div class="modal-box__container">
        <div class="modal-box__content">
          <div class="modal__desc">
            <p class="modal__text">
              다른 브라우저에서 접속이 감지되었습니다.<br> 
              로그아웃됩니다.
            </p>
          </div>
          <div class="modal__util">
            <button type="button" onclick="closeModal('#modal-ALT-02');" class="modal__button"><span>확인</span></button>
          </div>
          </div>
        </div>
      </div>
  </div>
</div>

<div id="modal-ALT-03" class="modal">
  <div class="modal__container" style="width: 350px;">
    <div class="modal__content">
      <div class="modal-box__container">
        <div class="modal-box__content">
          <div class="modal__desc">
            <p class="modal__text">
             작성 중인 내용이 있습니다. 진행을 취소하시겠습니까?
            </p>
          </div>
          <div class="modal__util">
            <button type="button" onclick="closeModal('#modal-ALT-03');" class="modal__button modal__button--gray"><span>취소</span></button>
            <button type="button" onclick="closeModal('#modal-ALT-03');" class="modal__button"><span>확인</span></button>
          </div>
          </div>
        </div>
      </div>
  </div>
</div>

<div id="modal-ALT-04" class="modal">
  <div class="modal__container" style="width: 350px;">
    <div class="modal__content">
      <div class="modal-box__container">
        <div class="modal-box__content">
          <div class="modal__desc">
            <p class="modal__text">
             삭제하시겠습니까?
            </p>
          </div>
          <div class="modal__util">
            <button type="button" onclick="closeModal('#modal-ALT-04');" class="modal__button modal__button--gray"><span>취소</span></button>
            <button type="button" onclick="closeModal('#modal-ALT-04');" class="modal__button"><span>확인</span></button>
          </div>
          </div>
        </div>
      </div>
  </div>
</div>


<div id="modal-ALT-05" class="modal">
  <div class="modal__container" style="width: 350px;">
    <div class="modal__content">
      <div class="modal-box__container">
        <div class="modal-box__content">
          <div class="modal__desc">
            <p class="modal__text">
              삭제 완료되었습니다.
            </p>
          </div>
          <div class="modal__util">
            <button type="button" onclick="closeModal('#modal-ALT-05');" class="modal__button"><span>확인</span></button>
          </div>
          </div>
        </div>
      </div>
  </div>
</div>

<div id="modal-ALT-06" class="modal">
  <div class="modal__container" style="width: 350px;">
    <div class="modal__content">
      <div class="modal-box__container">
        <div class="modal-box__content">
          <div class="modal__desc">
            <p class="modal__text">
              링크가 복사되었습니다.
            </p>
          </div>
          <div class="modal__util">
            <button type="button" onclick="closeModal('#modal-ALT-06');" class="modal__button"><span>확인</span></button>
          </div>
          </div>
        </div>
      </div>
  </div>
</div>

<div id="modal-ALT-07" class="modal">
  <div class="modal__container" style="width: 350px;">
    <div class="modal__content">
      <div class="modal-box__container">
        <div class="modal-box__content">
          <div class="modal__desc">
            <p class="modal__text">
              입력한 정보가 저장되었습니다.
            </p>
          </div>
          <div class="modal__util">
            <button type="button" onclick="closeModal('#modal-ALT-07');" class="modal__button"><span>확인</span></button>
          </div>
          </div>
        </div>
      </div>
  </div>
</div>











