<footer class="footer">
  <div class="inner">
    <div class="foo__cont">
      <div class="foo__wrap">
        <div class="foo__info">
          <p class="foo__logo"><span class="a11y">All FURN</span></p>
          <dl class="foo__flex">
            <dt>사업자등록번호 :&nbsp;</dt>
            <dd>128-19-60759</dd>
            <dt>대표 :&nbsp;</dt>
            <dd>박복숙</dd>
          </dl>
          <dl class="foo__flex">
            <dt>Tel :&nbsp;</dt>
            <dd>031-925-2888</dd>
            <dt>E-mail :&nbsp;</dt>
            <dd>
              <a href="mailto:gaguoutlet11@naver.com">gaguoutlet11@naver.com</a>
            </dd>
          </dl>
          <dl class="foo__flex">
            <dt>주소 :&nbsp;</dt>
            <dd>경기도 고양시 일산서구 송산로 23 (구산동 1477-3)</dd>
          </dl>
        </div>
        <div class="foo__customer">
          <a href="#">자주 묻는 질문</a>
          <a href="#">1:1 문의</a>
          <a href="#">이용 가이드</a>
        </div>
        <div class="foo__language">
          <p>한국어</p>
        </div>
      </div>
    </div>
    <div class="foo__util">
      <a href="#">서비스 소개</a>
      <a href="#">이용 약관</a>
      <a href="#">개인정보 처리 방침</a>
    </div>
  </div>

  <a href="#" title="추가하기" class="add-button">
    <img src="@@webroot/assets/images/temp/ico_plus@2x.png" alt="추가" />
  </a>
</footer>

<script
  src="@@webroot/assets/js/plugin/jquery-3.6.0.min.js"
  type="text/javascript"
></script>
<script src="@@webroot/assets/js/component.js" type="text/javascript"></script>
