<footer class="footer">
  <div class="inner">
    <div class="foo__cont">
      <p class="foo__logo"><span class="a11y">All FURN</span></p>
    </div>
    <div class="foo__util">
      <a href="#">서비스 소개</a>
      <a href="#">이용 약관</a>
      <a href="#">개인정보 처리 방침</a>
    </div>
  </div>

  <a href="#" title="추가하기" class="add-button">
    <img src="./assets/images/temp/ico_plus@2x.png" alt="추가">
  </a>
</footer>

<script src="@@webroot/assets/js/plugin/jquery-3.6.0.min.js" type="text/javascript"></script>