
<footer class="footer footer__mo">
    <div class="foo__cont">
        <div class="foo__wrap">
            <div>
                <p class="foo__logo"><span class="a11y">All FURN</span></p>
                <div class="foo__info">
                    <p>
                        사업자등록번호 : 182-81-02804<span class="bar"></span>대표 : 송도현
                    </p>
                    <p>주소 : 경기도 고양시 일산동구 산두로213번길 18(정발산동)</p>
                    <p>
                        Tel : 031-925-2888<span class="bar"></span>E-mail :
                        <a href="mailto:gaguoutlet11@naver.com">gaguoutlet11@naver.com</a>
                    </p>
                </div>
            </div>

            <div class="foo__customer">
                <p>고객센터 <i class="ico__arrow-mo-footer-down"></i></p>
                <a href="#">자주 묻는 질문</a>
                <a href="#">공지사항</a>
                <a href="#">1:1 문의</a>
                <a href="#">이용 가이드</a>
            </div>
        </div>
    </div>
    <div class="foo__util">
        <a href="#">서비스 소개</a><span class="bar"></span>
        <a href="#">이용 약관</a><span class="bar"></span>
        <a href="#">개인정보 처리 방침</a>
    </div>
</footer>

<div id="modal-page-notfund" class="modal">
    <div class="modal__container" style="width: 350px;">
        <div class="modal__content">
            <div class="modal-box__container">
                <div class="modal-box__content">
                    <div class="modal__desc">
                        <p class="modal__text">
                            존재하지 않는 화면입니다.
                        </p>
                    </div>
                    <div class="modal__util">
                        <button type="button" onclick="closeModal('#modal-page-notfund');"
                            class="modal__button"><span>확인</span></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="@@webroot/assets/js/ui.js" type="text/javascript"></script>
