<header id="header" class="header @@headertype">
  <div class="head__fixed">
    <div class="inner">
      <div class="head__flex">
        <h1 class="head__logo"><a href="/"><span class="a11y">All FURN</span></a></h1>

        <div class="textfield">
          <i class="textfield__icon ico__search"><span class="a11y">검색</span></i>
          <input
            type="text"
            class="textfield__search"
            placeholder="상품 및 도매 업체를 검색해주세요"
            style="width: 400px"
          />
          <button type="button" class="textfield__icon--delete ico__sdelete">
            <span class="a11y">삭제하기</span>
          </button>
        </div>
      </div>

      <div class="head__util">
        <div class="util__link">
          <a href="#">올톡</a>
          <a href="#">마이올펀</a>
          <a href="#">고객센터</a>
          <a href="#">
            <i class="ico__alram"><span class="a11y">알람</span></i>
            <span class="badge">99</span>
          </a>
          <a href="#">
            <i class="ico__basket"><span class="a11y">장바구니</span></i>
             <span class="badge">99</span>
          </a>
        </div>
      </div>
    </div>

    <div class="head__gnb">
      <div class="inner">
        <ul class="gnb__menu">
          <li><a href="#">카테고리</a></li>
          <li><a href="#">신상품</a></li>
          <li><a href="#">도매 업체</a></li>
          <li><a href="#">이 달의 도매</a></li>
          <li><a href="#">매거진</a></li>
          <li><a href="#">커뮤니티</a></li>
        </ul>
      </div>
    </div>
  </div>
</header>
