<header id="header" class="header @@headertype">
  <div class="head__fixed">
    <div class="inner">
      <div class="head__flex">
        <h1 class="head__logo"><a href="../home/GGTW-WEB-HME-01.html"><span class="a11y">All FURN</span></a></h1>

        <div class="textfield">
          <i class="textfield__icon ico__search"><span class="a11y">검색</span></i>
          <input
            type="text"
            class="textfield__search"
            placeholder="상품 및 도매 업체를 검색해주세요"
          />
          <button type="button" class="textfield__icon--delete ico__sdelete">
            <span class="a11y">삭제하기</span>
          </button>
        </div>
        <button type="button" class="globalsearch-close">취소</button>
      </div>

      <div class="head__util">
        <div class="util__link">
          <a href="#">올톡</a>
          <a href="#">마이올펀</a>
          <a href="#">고객센터</a>
          <a href="#">
            <i class="ico__alram"><span class="a11y">알람</span></i>
            <span class="badge">99</span>
          </a>
          <a href="#">
            <i class="ico__basket"><span class="a11y">장바구니</span></i>
             <span class="badge">99</span>
          </a>
        </div>
      </div>
    </div>
    <div class="head__gnb">
      <div class="inner">
        <ul class="gnb__menu">
          <li><a href="#" class="category-select">카테고리</a></li>
          <li><a href="../product/GGTW-WEB-PDL-01.html">신상품</a></li>
          <li><a href="../wholesaler/GGTW-WEB-WSC-01.html">도매 업체</a></li>
          <li><a href="../wholesaler/GGTW-WEB-WSP-01.html">이 달의 도매</a></li>
          <li><a href="../magazine/GGTW-WEB-MGZ-01.html">매거진</a></li>
          <li><a href="../community/GGTW-WEB-CMT-01.html">커뮤니티</a></li>
        </ul>

        <div class="gnb__category">
          <div class="category-list-wrap">
            <ul class="category-wrap">
              <li>
                <a href="#" class="category-list01">
                  <img class="category__ico" src="../assets/images/sub/ico_furniture_01.png" alt="침실 아이콘">
                  <span>침실</span>
                </a>
              </li>
              <li>
                <a href="#" class="category-list02">
                  <img class="category__ico" src="../assets/images/sub/ico_furniture_02.png" alt="소파/거실 아이콘">
                  <span>소파/거실</span>
                </a>
              </li>
              <li>
                <a href="#" class="category-list03">
                  <img class="category__ico" src="../assets/images/sub/ico_furniture_03.png" alt="식탁/의자 아이콘">
                  <span>식탁/의자</span>
                </a>
              </li>
              <li>
                <a href="#" class="category-list04">
                  <img class="category__ico" src="../assets/images/sub/ico_furniture_04.png" alt="옷장/수납장/서랍장 아이콘">
                  <span>옷장/수납장/서랍장</span>
                </a>
              </li>
              <li>
                <a href="#" class="category-list05">
                  <img class="category__ico" src="../assets/images/sub/ico_furniture_05.png" alt="서재/공부방 아이콘">
                  <span>서재/공부방</span>
                </a>
              </li>
              <li>
                <a href="#" class="category-list06">
                  <img class="category__ico" src="../assets/images/sub/ico_furniture_06.png" alt="화장대/거울/콘솔 아이콘">
                  <span>화장대/거울/콘솔</span>
                </a>
              </li>
              <li>
                <a href="#" class="category-list07">
                  <img class="category__ico" src="../assets/images/sub/ico_furniture_07.png" alt="키즈/주니어 아이콘">
                  <span>키즈/주니어</span>
                </a>
              </li>
              <li>
                <a href="#" class="category-list08">
                  <img class="category__ico" src="../assets/images/sub/ico_furniture_08.png" alt="진열장/장식장 아이콘">
                  <span>진열장/장식장</span>
                </a>
              </li>
              <li>
                <a href="#" class="category-list09">
                  <img class="category__ico" src="../assets/images/sub/ico_furniture_09.png" alt="안락의자/기능성의자 아이콘">
                  <span>안락의자/기능성의자</span>
                </a>
              </li>
              <li>
                <a href="#" class="category-list10">
                  <img class="category__ico" src="../assets/images/sub/ico_furniture_10.png" alt="테이블/의자 아이콘">
                  <span>테이블/의자</span>
                </a>
              </li>
              <li>
                <a href="#" class="category-list11">
                  <img class="category__ico" src="../assets/images/sub/ico_furniture_11.png" alt="선반 아이콘">
                  <span>선반</span>
                </a>
              </li>
              <li>
                <a href="#" class="category-list12">
                  <img class="category__ico" src="../assets/images/sub/ico_furniture_12.png" alt="아웃도어가구 아이콘">
                  <span>아웃도어가구</span>
                </a>
              </li>
              <li>
                <a href="#" class="category-list13">
                  <img class="category__ico" src="../assets/images/sub/ico_furniture_13.png" alt="소품가구/기타 아이콘">
                  <span>소품가구/기타</span>
                </a>
              </li>
              <li>
                <a href="#" class="category-list14">
                  <img class="category__ico" src="../assets/images/sub/ico_furniture_14.png" alt="사무용가구 아이콘">
                  <span>사무용가구</span>
                </a>
              </li>
            </ul>

            <ul class="category-wrap--active">
              <li>
                <a href="#">
                  <span>전체</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span>일반소파</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span>1인용의자</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span>리클라이너</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span>소파스툴</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span>소파베드</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span>좌식소파</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span>소파테이블</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span>거실장</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span>TV스탠드</span>
                </a>
              </li>
            </ul>
          </div>

          <div class="category-banner-wrap">
            <div id="eventkvSwipeHeader" class="eventkeyvisual swiper-container category-banner">
              <div class="swiper-wrapper">
                <div class="swiper-slide">
                  <a href="#">
                    <p class="event__banner" style="background-image:url(/assets/images/temp/banner_event.png)"></p>
                  </a>
                </div>
                <div class="swiper-slide">
                  <a href="#">
                    <p class="event__banner" style="background-image:url(/assets/images/temp/banner_event.png)"></p>
                  </a>
                </div>
              </div>
              <div class="swiper-util">
                <div>
                  <div class="swiper-pagination"></div>
                </div>
              </div>
              <div class="swiper-button-prev"></div>
              <div class="swiper-button-next"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

<div id="globalsearch" class="globalsearch">
  <div class="globalsearch__inner">
    <div class="globalsearch__section globalsearch__section--history">
      <!-- 검색 기록 -->
      <div class="globalsearch-history" aria-hidden="false">
        <div class="row">
          <div class="title">최근 검색어</div>
          <div class="head-button"><a role="button" class="head-button">전체 삭제</a></div>
        </div>
        <div class="row">
          <div class="row__text">리바트 소파 베드</div>
          <a role="button">
            <div class="ico__delete10"><span class="a11y">삭제하기</span></div>
          </a>
        </div>
        <div class="row">
          <div class="row__text">3인 소파</div>
          <a role="button">
            <div class="ico__delete10"><span class="a11y">삭제하기</span></div>
          </a>
        </div>
        <div class="row">
          <div class="row__text">코윈스</div>
          <a role="button">
            <div class="ico__delete10"><span class="a11y">삭제하기</span></div>
          </a>
        </div>
        <div class="row">
          <div class="row__text">라자가구</div>
          <a role="button">
            <div class="ico__delete10"><span class="a11y">삭제하기</span></div>
          </a>
        </div>
        <div class="row">
          <div class="row__text">대화 목록에서 업체를 선택하세요. 대화 목록에서 대화 목록에서 업체하여 메세지를 확인하세요.</div>
          <a role="button">
            <div class="ico__delete10"><span class="a11y">삭제하기</span></div>
          </a>
        </div>
      </div>
      <!--// 검색 기록 -->
      <!-- 검색 기록 없음 -->
      <div class="globalsearch-history globalsearch-history--empty" aria-hidden="true" style="display: none;">
        <div class="row">
          <div class="title">최근 검색어</div>
        </div>
        <div class="empty">최근 검색한 내역이 없습니다.</div>
      </div>
      <!--// 검색 기록 없음 -->
    </div>
    <div class="globalsearch__section globalsearch__section--best">
      <!-- 인기 집계 -->
      <div class="globalsearch-best" aria-hidden="false">
        <div class="row">
          <div class="title">
            인기 카테고리
            <div class="title-meta"><span>05.02</span><span>12:00</span><span>기준</span></div>
          </div>
        </div>
        <div class="row">
          <div class="numbering">1</div>
          <a href="/category/GGTW-WEB-CTG-03.html">
            <ul class="breadcrumbs-wrap">
              <li>안락의자/기능성의자</li>
              <li>스툴</li>
            </ul>
          </a>
        </div>
        <div class="row">
          <div class="numbering">2</div>
          <a href="/category/GGTW-WEB-CTG-03.html">
            <ul class="breadcrumbs-wrap">
              <li>소파/거실</li>
              <li>리클라이너</li>
            </ul>
          </a>
        </div>
        <div class="row">
          <div class="numbering">3</div>
          <a href="/category/GGTW-WEB-CTG-03.html">
            <ul class="breadcrumbs-wrap">
              <li>아웃도어가구</li>
              <li>파라솔</li>
            </ul>
          </a>
        </div>
        <div class="row">
          <div class="numbering">4</div>
          <a href="/category/GGTW-WEB-CTG-03.html">
            <ul class="breadcrumbs-wrap">
              <li>옷장/수납/서랍장</li>
              <li>수납장</li>
            </ul>
          </a>
        </div>
        <div class="row">
          <div class="numbering">5</div>
          <a href="/category/GGTW-WEB-CTG-03.html">
            <ul class="breadcrumbs-wrap">
              <li>사무용가구</li>
              <li>책장/캐비닛/사물함</li>
            </ul>
          </a>
        </div>
      </div>
      <!--// 인기 집계 -->
      <!-- 인기 집계 없음 -->
      <div class="globalsearch-best globalsearch-best--empty" aria-hidden="true" style="display: none;">
        <div class="row">
          <div class="title">
            인기 카테고리
            <div class="title-meta"><span>05.02</span><span>12:00</span><span>기준</span></div>
          </div>
        </div>
        <div class="empty">집계된 인기 카테고리가 없습니다.</div>
      </div>
      <!--// 인기 집계 없음 -->
    </div>
    <div class="globalsearch__section globalsearch__section--recommend">
      <div class="globalsearch-recommend">
        <div class="row">
          <div class="title">
            추천 키워드
            <div class="title-meta"><span>AD</span></div>
          </div>
        </div>
        <div class="row">
          <div class="hashtag-list">
            <div class="hashtag">코윈스</div>
            <div class="hashtag">라자가구</div>
            <div class="hashtag">허그앤슬립</div>
            <div class="hashtag">천연가죽 라운드 소파</div>
            <div class="hashtag">올펀</div>
            <div class="hashtag">가구톡세상</div>
          </div>
        </div>
      </div>
    </div>
    <div class="globalsearch__banner">
      <div id="headerNavBanner" class="swiper-container">
        <div class="swiper-util">
          <div class="swiper-pagination">
            <div class="swiper-pagination-current"></div> / <div class="swiper-pagination-total"></div>
          </div>
          <div class="carousel-nav-next ico__carousel-right"></div>
          <div class="carousel-nav-prev ico__carousel-left"></div>
        </div>
        <div class="swiper-wrapper">
          <div class="swiper-slide">
            <a href="#">
              <p class="event__banner" style="background-image:url(/assets/images/temp/headernav_banner_1.png)"></p>
            </a>
          </div>
          <div class="swiper-slide">
            <a href="#">
              <p class="event__banner" style="background-image:url(/assets/images/temp/headernav_banner_1.png)"></p>
            </a>
          </div>
          <div class="swiper-slide">
            <a href="#">
              <p class="event__banner" style="background-image:url(/assets/images/temp/headernav_banner_1.png)"></p>
            </a>
          </div>
          <div class="swiper-slide">
            <a href="#">
              <p class="event__banner" style="background-image:url(/assets/images/temp/headernav_banner_1.png)"></p>
            </a>
          </div>
          <div class="swiper-slide">
            <a href="#">
              <p class="event__banner" style="background-image:url(/assets/images/temp/headernav_banner_1.png)"></p>
            </a>
          </div>
          <div class="swiper-slide">
            <a href="#">
              <p class="event__banner" style="background-image:url(/assets/images/temp/headernav_banner_1.png)"></p>
            </a>
          </div>
          <div class="swiper-slide">
            <a href="#">
              <p class="event__banner" style="background-image:url(/assets/images/temp/headernav_banner_1.png)"></p>
            </a>
          </div>
          <div class="swiper-slide">
            <a href="#">
              <p class="event__banner" style="background-image:url(/assets/images/temp/headernav_banner_1.png)"></p>
            </a>
          </div>
          <div class="swiper-slide">
            <a href="#">
              <p class="event__banner" style="background-image:url(/assets/images/temp/headernav_banner_1.png)"></p>
            </a>
          </div>
          <div class="swiper-slide">
            <a href="#">
              <p class="event__banner" style="background-image:url(/assets/images/temp/headernav_banner_1.png)"></p>
            </a>
          </div>
          <div class="swiper-slide">
            <a href="#">
              <p class="event__banner" style="background-image:url(/assets/images/temp/headernav_banner_1.png)"></p>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="globalsearch-insearch">
      <div class="globalsearch-insearch__inner">
        <div class="row">
          <div class="ico__search20"><span class="a11y">검색</span></div>
          <a href="/">
            <ul class="breadcrumbs-wrap">
              <li><span class="selection">소파</span>/거실</li>
              <li>전체</li>
            </ul>
          </a>
        </div>
        <div class="row">
          <div class="ico__search20"><span class="a11y">검색</span></div>
          <a href="/">
            <ul class="breadcrumbs-wrap">
              <li><span class="selection">소파</span>/거실</li>
              <li><span class="selection">소파</span>베드</li>
            </ul>
          </a>
        </div>
        <div class="row">
          <div class="ico__search20"><span class="a11y">검색</span></div>
          <a href="/">
            <ul class="breadcrumbs-wrap">
              <li><span class="selection">소파</span>/거실</li>
              <li>일반<span class="selection">소파</span></li>
            </ul>
          </a>
        </div>
        <div class="row">
          <div class="ico__search20"><span class="a11y">검색</span></div>
          <a href="/">
            <ul class="breadcrumbs-wrap">
              <li><span class="selection">소파</span>/거실</li>
              <li>2인용의자</li>
            </ul>
          </a>
        </div>
        <div class="row">
          <div class="ico__search20"><span class="a11y">검색</span></div>
          <a href="/">
            <ul class="breadcrumbs-wrap">
              <li><span class="selection">소파</span>/거실</li>
              <li>1인용의자</li>
            </ul>
          </a>
        </div>
        <div class="row">
          <div class="ico__search20"><span class="a11y">검색</span></div>
          <a href="/">
            <ul class="breadcrumbs-wrap">
              <li><span class="selection">소파</span>/거실</li>
              <li>TV스탠드</li>
            </ul>
          </a>
        </div>
        <div class="row">
          <div class="ico__search20"><span class="a11y">검색</span></div>
          <a href="/">
            <ul class="breadcrumbs-wrap">
              <li><span class="selection">소파</span>/거실</li>
              <li>3인<span class="selection">소파</span></li>
            </ul>
          </a>
        </div>
        <div class="row">
          <div class="ico__search20"><span class="a11y">검색</span></div>
          <a href="/">
            <ul class="breadcrumbs-wrap">
              <li><span class="selection">소파</span>/거실</li>
              <li>리클라이너</li>
            </ul>
          </a>
        </div>
        <div class="row">
          <div class="ico__search20"><span class="a11y">검색</span></div>
          <a href="/">
            <ul class="breadcrumbs-wrap">
              <li><span class="selection">소파</span>/거실</li>
              <li><span class="selection">소파</span>스툴</li>
            </ul>
          </a>
        </div>
        <div class="row">
          <div class="ico__search20"><span class="a11y">검색</span></div>
          <a href="/">
            <ul class="breadcrumbs-wrap">
              <li><span class="selection">소파</span>/거실</li>
              <li><span class="selection">소파</span>테이블</li>
            </ul>
          </a>
        </div>
        <div class="row">
          <div class="ico__search20"><span class="a11y">검색</span></div>
          <a href="/">
            <ul class="breadcrumbs-wrap">
              <li><span class="selection">소파</span>/거실</li>
              <li>거실장</li>
            </ul>
          </a>
        </div>
        <div class="row">
          <div class="ico__search20"><span class="a11y">검색</span></div>
          <a href="/">
            <ul class="breadcrumbs-wrap">
              <li><span class="selection">소파</span>/거실</li>
              <li>전체</li>
            </ul>
          </a>
        </div>
        <div class="row">
          <div class="ico__search20"><span class="a11y">검색</span></div>
          <a href="/">
            <ul class="breadcrumbs-wrap">
              <li><span class="selection">소파</span>/거실</li>
              <li>일반<span class="selection">소파</span></li>
            </ul>
          </a>
        </div>
        <div class="row">
          <div class="ico__search20"><span class="a11y">검색</span></div>
          <a href="/">
            <ul class="breadcrumbs-wrap">
              <li><span class="selection">소파</span>/거실</li>
              <li>1인용의자</li>
            </ul>
          </a>
        </div>
        <div class="row">
          <div class="ico__search20"><span class="a11y">검색</span></div>
          <a href="/">
            <ul class="breadcrumbs-wrap">
              <li><span class="selection">소파</span>/거실</li>
              <li>TV스탠드</li>
            </ul>
          </a>
        </div>
        <div class="row">
          <div class="ico__search20"><span class="a11y">검색</span></div>
          <a href="/">
            <ul class="breadcrumbs-wrap">
              <li><span class="selection">소파</span>/거실</li>
              <li>리클라이너</li>
            </ul>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="globalsearch-modal" class="globalsearch-modal"></div>
