<header id="header" class="header @@headertype">
	<div class="head__fixed">
    <div class="inner">
      <h1 class="head__logo"><span class="a11y">All FURN</span></h1>

      <div class="head__search">
        <input type="text" placeholder="상품 및 도매 업체를 검색해주세요">
      </div>
      <div class="head__util">
        <div class="util__link">
          <a href="#">올톡</a>
          <a href="#">마이올펀</a>
          <a href="#">고객센터</a>
        </div>
      </div>
    </div>
  </div>

  <div class="head__gnb">
    <div class="inner">
      <ul class="gnb__menu">
        <li><a href="#">카테고리</a></li>
        <li><a href="#">신상품</a></li>
        <li><a href="#">도매 업체</a></li>
        <li><a href="#">이 달의 도매</a></li>
        <li><a href="#">매거진</a></li>
        <li><a href="#">커뮤니티</a></li>
      </ul>
    </div>
  </div>
</header>