<!DOCTYPE html>
<html lang="ko_KR">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="keywords" content=""/>
  <meta name="description" content=""/>  
  <meta property="og:locale" content="ko_KR" />
  <meta property="og:type" content="website" />
  <meta property="og:title" content="" />
  <meta property="og:keywords" content="" />
  <meta property="og:description" content="" />
  <meta property="og:url" content="#" />
  <meta property="og:image" content="">
  <meta property="og:site_name" content="" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:description" content="" />
  <meta name="twitter:title" content="" />
  <!-- <link rel="icon" href="@@webroot/assets/images/common/favicon.png" sizes="32x32" />
  <link rel="icon" href="@@webroot/assets/images/common/favicon.png" sizes="192x192" />
  <link rel="apple-touch-icon" href="" /> -->
  
	<title>All FURN @@pagetitle</title>

  <script src="@@webroot/assets/js/plugin/jquery-3.6.0.min.js" type="text/javascript"></script>
   <script src="@@webroot/assets/js/plugin/jquery-ui-1.13.1.js" type="text/javascript"></script>
	<link rel="stylesheet" href="@@webroot/assets/css/ui.css">
</head>